### PR TITLE
Rotation power/time fix + cleanup 

### PR DESCRIPTION
**Pull request by bisc**
Fixed incorrect rotation power/time calculation + minor cleanup for the generation and the model. 

Now in the generated prism model, the rotation time cannot be negative, and the smallest rotation energy is in the direction where the robot is facing. MapTranslator.findArcOrientation(double, double, double, double) contains the fix.

### CODE REVIEW

**Comment by bisc** [comment]
Another externally noticeable change: running MapTranslator standalone requires setting PRISMBIN and PRISMOUTDIR environment variables (to avoid hardcoded absolute paths).

**Comment by schmerl** [comment]
Javier, I think this is better for you to look at. You can see what changes were made in the files changed tab of this pull request.

**Comment by bisc** [comment]
Ping @javier-camara

**Comment by bisc** [comment]
Ping @schmerl

**Pull request merged**
